version: 2.1

workflows:
  version: 2
  build-workflow:
    jobs:
    - build

jobs:
  build:
    docker:
    # primary image for building app
    - image: cimg/go:1.16-node

    # service images available at `host: localhost`
    - image: circleci/postgres:12-alpine
      environment:
        POSTGRES_USER: dev-user
        POSTGRES_PASSWORD: dev-secret
        POSTGRES_DB: my_postgres_db

    - image: circleci/mysql:5.7
      environment:
        MYSQL_DATABASE: mysql
        MYSQL_ROOT_PASSWORD: my-secret-pw

    - image: circleci/mongo:4.4
      environment:
        MONGO_INITDB_ROOT_USERNAME: mongoadmin
        MONGO_INITDB_ROOT_PASSWORD: super-secret

    - image: circleci/redis:5.0

    steps:
    - checkout

    # unit tests
    - run: make test

    # build binary
    - run: make build
    - run:
        name: install binary
        command: |
          chmod +x /home/circleci/project/backman
          sudo cp /home/circleci/project/backman /usr/local/bin/backman
          sudo chmod +x /usr/local/bin/backman

    # minIO server
    - run:
        name: run minIO server
        command: |
          wget https://dl.min.io/server/minio/release/linux-amd64/minio -qO minio
          chmod +x minio
          sudo mv minio /usr/local/bin/minio
          minio server /tmp/data
        background: true
        environment:
          MINIO_UPDATE: 'off'
          MINIO_ACCESS_KEY: 6d611e2d-330b-4e52-a27c-59064d6e8a62
          MINIO_SECRET_KEY: eW9sbywgeW91IGhhdmUganVzdCBiZWVuIHRyb2xsZWQh

    # killall
    - run:
        name: install killall
        command: |
          sudo apt-get update
          sudo apt-get -y install psmisc

    # jq
    - run:
        name: install jq
        command: |
          wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -qO jq
          chmod +x jq
          sudo mv jq /usr/local/bin/jq

    # postgres integration tests
    - run:
        name: install Postgres client
        command: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt buster-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get -y install postgresql-client-12
    - run: make postgres-test

    # mongodb integration tests
    - run:
        name: install MongoDB client
        command: |
          wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-database-tools=100.5.1 mongodb-org-tools=5.0.5 mongodb-org-shell=5.0.5
    - run: make mongodb-test

    # redis integration tests
    - run:
        name: install Redis client
        command: sudo apt install -y redis-tools
    - run: make redis-test

    # mysql integration tests
    - run:
        name: install MySQL client
        command: sudo apt install -y mariadb-client
    - run: make mysql-test
