name: dockerhub image

on:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  dockerhub-image:
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: dockerhub login
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: extract metadata (tags, labels) for docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: jamesclonk/backman
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: build and push docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
