name: snyk golang scan

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  snyk-golang:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run snyk to for golang vulnerabilities
      continue-on-error: true
      uses: snyk/actions/golang@dc22abdbe8ec00e2a925256fef96f319ca5510ce
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --policy-path=. --file=go.mod --sarif-file-output=snyk.sarif --fail-on=all
    - name: upload results to github code scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif
